name: Android CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  ci-build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Mock files for CI
      run: |
        rm ./app/google-services.json
        cp ./app/google-services-example.json ./app/google-services.json
        rm ./app/src/main/res/values/curfirmwareversion.xml
        cp ./app/special/curfirmwareversion.xml ./app/src/main/res/values/

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Upload F-Droid APK
      uses: actions/upload-artifact@v3
      with:
        name: fdroidDebug
        path: app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk
        retention-days: 30

    - name: Upload Google APK
      uses: actions/upload-artifact@v3
      with:
        name: googleDebug
        path: app/build/outputs/apk/google/debug/app-google-debug.apk
        retention-days: 30
